#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Render the IEA 15-240-RWT rated-point case from the committed P0/P1 data.

The case skeleton mirrors the NREL Phase VI uniform-inflow case
(``validation/phaseVI/tools/generate_case.py``) scaled to the 15 MW rotor:
an 18-block hexahedral far-field box, the same boundary layout, the same
URANS solver/schemes and an ``axialFlowTurbineALSource`` neutral baseline.

Sources of truth (never edited here):

- ``data/iea15mw_blade.csv`` (P0) — chord, twist, chord mount and the ALM
  mounting angle for all 50 stations.
- ``data/polars/polar_NN.dat`` (P1) — one ``profileData`` polar per station.

Operating point (rated, below the rated wind speed of the reference):
``V = 10.659 m/s``, ``Omega = 7.518 rpm``, collective pitch ``0``.  The tip
speed ratio is *computed* as ``Omega*R/V`` with the P0 projected radius
``R = 120.67532316 m`` — it is not a guessed constant.

Precone decision (option b): the ``elementData`` radius column is the
*physical* along-blade radius (``HubRad + BlSpn``, tip 120.9699 m) and the
rotor is rendered with ``coneAngle 4``.  ``axialFlowTurbineALSource``
supports the cone directly (``coneAngle`` is a documented
``lookupOrDefault`` key, ``axialFlowTurbineALSource.C:83``), so the extra key
is the only cost, and it preserves the real blade geometry while the
projected tip lands exactly on ``rotorRadius``:
``120.9699*cos(4 deg) = 120.6753 m``.

Blade shape (AeroDyn v15): ``elementData`` also carries the prebend
(``axialDistance = -BlCrvAC``), the sweep (``azimuth = asin(BlSwpAC/radius)``)
and the curve angle (``curveAngle = BlCrvAng``, 7th column, tilting the ALM
section frame).  See ``odd/tasks/iea15mw-blade-geometry-mapping.md``.

Every generated file carries a "Generated by tools/generate_case.py" banner;
``--check`` re-renders in memory and fails when a file on disk is missing or
stale, without writing anything.

Usage:
    generate_case.py [--speed 10.659] [--rpm 7.518] [--pitch 0]
                     [--mesh coarse] [--n-elements 147] [--cone-angle 4]
                     [--end-revs 3] [--start-from startTime|latestTime]
                     [--flow-axis x|y] [--case-dir DIR] [--check]
"""

from __future__ import annotations

import argparse
import difflib
import math
import os
import sys
from pathlib import Path
from typing import Any

TOOLS_DIR = Path(__file__).resolve().parent
PACKAGE = TOOLS_DIR.parent
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

import blade_geometry  # noqa: E402

#: Committed P0/P1 inputs.
BLADE_CSV = PACKAGE / "data" / "iea15mw_blade.csv"
POLARS_DIR = PACKAGE / "data" / "polars"
DEFAULT_CASE_DIR = PACKAGE / "case"

# --- Rated operating point (NREL/TP-5000-75698 Table 3-1) --------------------
RATED_SPEED = 10.659
RATED_RPM = 7.518
RATED_PITCH_DEG = 0.0

# --- Rotor geometry (P0 radius decision) -------------------------------------
ROTOR_RADIUS = blade_geometry.ROTOR_RADIUS_PUBLISHED
ROTOR_DIAMETER = 2.0 * ROTOR_RADIUS
HUB_HEIGHT = 150.0
N_BLADES = 3
#: 50 geometry stations -> 49 segments; 147 = 3 elements per segment.
N_ELEMENTS = 147
#: 4 deg precone, applied through the source's `coneAngle` key (option b).
PRECONE_DEG = 4.0
#: WindIO nacelle overhang (hub-to-yaw-axis distance) is the tower offset source.
#: Tower ALM elements: the WindIO tower table has 11 unique stations (10 segments).
TOWER_N_ELEMENTS = 40

# --- Domain and mesh (ground-anchored, parametric) ---------------------------
#: Horizontal mesh resolutions: cells across the rotor diameter.
MESH_CHOICES = ("coarse", "medium", "fine")
MESH_D_OVER = {"coarse": 32.0, "medium": 48.0, "fine": 64.0}
#: Base (coarse, D/32) horizontal block breaks [D] and cells/grading. Other
#: resolutions and domain extents scale the cells proportionally, so the grading
#: (a ratio) and the relative resolution are preserved.
BASE_FLOW_BREAKS = (-5.0, -0.5, 8.0, 15.0)
BASE_LAT_BREAKS = (-4.0, -1.5, 1.5, 4.0)
BASE_FLOW_CELLS = (50, 272, 60)
BASE_LAT_CELLS = (36, 96, 36)
BASE_FLOW_GRADING = (0.160029, 1.0, 9.252929)
BASE_LAT_GRADING = (0.241240, 1.0, 4.145249)
#: Default domain extents [D] and top [m above the rotor].
DEFAULT_UPSTREAM_D = 5.0
DEFAULT_DOWNSTREAM_D = 15.0
DEFAULT_LATERAL_D = 4.0
DEFAULT_FINE_MAX_D = 8.0
DEFAULT_FINE_LAT_D = 1.5
DEFAULT_DOMAIN_TOP = 2.5 * ROTOR_DIAMETER
#: Ground-anchored vertical refinement: hub-adjacent and ground-adjacent cells [m].
Z_HUB_CELL = ROTOR_DIAMETER / 32.0
Z_GROUND_CELL = 2.0
Z_GROWTH = 1.06
#: Recorded expected cell count of the default ground-anchored coarse mesh.
EXPECTED_CELL_COUNT = 4_299_792


def domain_spec(
    mesh: str = "coarse",
    upstream: float = DEFAULT_UPSTREAM_D,
    downstream: float = DEFAULT_DOWNSTREAM_D,
    lateral: float = DEFAULT_LATERAL_D,
    fine_max: float = DEFAULT_FINE_MAX_D,
    fine_lat: float = DEFAULT_FINE_LAT_D,
    top: float = DEFAULT_DOMAIN_TOP,
) -> dict[str, float | str]:
    """Bundle the parametric domain/mesh definition (D units, and top in m)."""
    if mesh not in MESH_D_OVER:
        raise KeyError(f"unsupported mesh {mesh!r}; choose from {MESH_CHOICES}")
    if not (0.0 < upstream and 0.0 < lateral and downstream > upstream):
        raise ValueError("domain extents must satisfy downstream > upstream > 0")
    return {
        "mesh": mesh,
        "upstream": float(upstream),
        "downstream": float(downstream),
        "lateral": float(lateral),
        "fine_max": float(fine_max),
        "fine_lat": float(fine_lat),
        "top": float(top),
    }


def _domain_breaks(domain: dict[str, float | str], axis: str) -> list[float]:
    up = float(domain["upstream"])
    down = float(domain["downstream"])
    lat = float(domain["lateral"])
    fmax = min(float(domain["fine_max"]), 0.9 * down)
    flat = min(float(domain["fine_lat"]), 0.5 * lat)
    d = {
        "x": (-up, -0.5, fmax, down),
        "y": (-lat, -flat, flat, lat),
    }[axis]
    return [ROTOR_DIAMETER * v for v in d]


def _scale_cells(
    cells: tuple[int, ...],
    base_breaks: tuple[float, ...],
    breaks: list[float],
    refinement: float,
) -> list[int]:
    """Scale the base cells for a new resolution/extent, keeping the cell size."""
    scaled = []
    for index, count in enumerate(cells):
        base_len = abs(base_breaks[index + 1] - base_breaks[index])
        new_len = abs(breaks[index + 1] - breaks[index])
        scaled.append(max(1, round(count * refinement * new_len / base_len)))
    return scaled


def flow_breaks(domain: dict[str, float | str]) -> list[float]:
    """Streamwise block breaks [m]."""
    return _domain_breaks(domain, "x")


def lateral_breaks(domain: dict[str, float | str]) -> list[float]:
    """Lateral block breaks [m]."""
    return _domain_breaks(domain, "y")


def flow_cells(domain: dict[str, float | str]) -> list[int]:
    refinement = MESH_D_OVER[str(domain["mesh"])] / MESH_D_OVER["coarse"]
    base = [ROTOR_DIAMETER * v for v in BASE_FLOW_BREAKS]
    return _scale_cells(BASE_FLOW_CELLS, base, flow_breaks(domain), refinement)


def lateral_cells(domain: dict[str, float | str]) -> list[int]:
    refinement = MESH_D_OVER[str(domain["mesh"])] / MESH_D_OVER["coarse"]
    base = [ROTOR_DIAMETER * v for v in BASE_LAT_BREAKS]
    return _scale_cells(BASE_LAT_CELLS, base, lateral_breaks(domain), refinement)


def delta_t(domain: dict[str, float | str], rpm: float = RATED_RPM) -> float:
    """Time step [s]: tip displacement per step stays below the hub-adjacent cell.

    Rounded to 3 significant figures so the coarse case keeps ``deltaT 0.075``.
    """
    tip_speed = omega_from_rpm(rpm) * ROTOR_RADIUS
    return float(f"{0.95 * hub_cell_size(domain) / tip_speed:.3g}")

# --- Decomposition (P3 plan) -------------------------------------------------
NUMBER_OF_SUBDOMAINS = 48

# --- Solver / inflow ---------------------------------------------------------
APPLICATION = "pimpleFoam"
TURBULENCE_MODEL = "kOmegaSST"
KINEMATIC_VISCOSITY = 1.5e-5
TURBULENCE_INTENSITY = 0.005
MIXING_LENGTH_D = 0.07
DEFAULT_END_REVOLUTIONS = 3
WRITE_INTERVAL_DEG = 5.0

PATCH_NAMES = ("inlet", "outlet", "bottom", "top", "sideMinus", "sidePlus")

#: Flow/rotor-axis orientation. ``x`` = the OpenFAST/AeroDyn convention (X
#: downwind); ``y`` = the Aeroelast/FSI convention (fluid in +Y, blade axis +Z,
#: profiles in XY), used so the fluid and structural meshes coincide for FSI.
FLOW_AXIS_CHOICES = ("x", "y")
#: Default orientation. ``y`` = the Aeroelast/FSI frame the IEA 15 MW case exists
#: for (fluid +Y, rotor axis about Y, blade axis +Z); ``x`` = OpenFAST.
DEFAULT_FLOW_AXIS = "y"


def inflow_direction(flow_axis: str = DEFAULT_FLOW_AXIS) -> tuple[float, float, float]:
    """Unit inflow direction: +x (OpenFAST) or +y (Aeroelast)."""
    if flow_axis == "x":
        return (1.0, 0.0, 0.0)
    if flow_axis == "y":
        return (0.0, 1.0, 0.0)
    raise ValueError(f"unknown flow axis {flow_axis!r}")


def rotor_axis(flow_axis: str = DEFAULT_FLOW_AXIS) -> tuple[float, float, float]:
    """Rotor axis (upwind, opposite the inflow)."""
    direction = inflow_direction(flow_axis)
    return tuple(-value for value in direction)


def _role_to_physical(
    flow_axis: str, x_role: float, y_role: float, z_role: float
) -> tuple[float, float, float]:
    """Map the mesh roles (x=flow, y=lateral, z=vertical) to physical XYZ.

    The y-flow case is the proper rotation ``R_z(+90 deg)`` — flow role -> +Y,
    lateral role -> -X, vertical unchanged — so the block handedness (and thus
    the blockMesh face normals) is preserved.
    """
    if flow_axis == "x":
        return (x_role, y_role, z_role)
    return (-y_role, x_role, z_role)


# ---------------------------------------------------------------------------
# Derived kinematics
# ---------------------------------------------------------------------------
def omega_from_rpm(rpm: float) -> float:
    """Rotor angular velocity [rad/s] from a shaft speed in rpm."""
    return float(rpm) * 2.0 * math.pi / 60.0


def tip_speed_ratio(speed: float, rpm: float, radius: float = ROTOR_RADIUS) -> float:
    """Tip speed ratio ``Omega*R/V`` from the operating point.

    Never hard-coded: the readiness note's proposed 9.0786 corresponds to
    7.6575 rpm, not the rated 7.518 rpm, so it is not reproduced here.
    """
    return omega_from_rpm(rpm) * float(radius) / float(speed)


def revolution_period(rpm: float) -> float:
    """One rotor revolution [s]."""
    return 2.0 * math.pi / omega_from_rpm(rpm)


def axis_extents(axis: str) -> list[float]:
    """Default-domain horizontal block extents [m] of one axis (x/y)."""
    domain = domain_spec()
    if axis == "x":
        return flow_breaks(domain)
    if axis == "y":
        return lateral_breaks(domain)
    raise KeyError(f"{axis!r} is not a horizontal axis (x/y)")


def _geometric_layer(length: float, first_cell: float, last_cell: float) -> tuple[int, float]:
    """Number of cells and OpenFOAM grading for a geometric layer [m].

    Returns ``(n, grading)`` with ``grading = last_cell/first_cell`` and ``n``
    chosen so the actual first cell is closest to ``first_cell``.
    """
    ratio = float(last_cell) / float(first_cell)
    best_n, best_err = 1, float("inf")
    for n in range(2, 4000):
        q = ratio ** (1.0 / (n - 1))
        first = float(length) * (q - 1.0) / (q**n - 1.0)
        err = abs(first - float(first_cell))
        if err < best_err:
            best_err, best_n = err, n
        if first < float(first_cell) * 0.5:
            break
    return best_n, ratio


def _growing_layer(length: float, first_cell: float, growth: float) -> tuple[int, float]:
    """Number of cells and grading for a layer growing at ``growth`` from
    ``first_cell`` over ``length``."""
    g = float(growth)
    n = max(
        1,
        int(
            math.ceil(
                math.log(1.0 + float(length) * (g - 1.0) / float(first_cell))
                / math.log(g)
            )
        ),
    )
    return n, g ** (n - 1)


def vertical_mesh(
    domain_top: float = DEFAULT_DOMAIN_TOP,
    mesh: str = "coarse",
) -> tuple[list[float], list[int], list[float]]:
    """Hub-anchored vertical mesh: breaks, cells and grading.

    The rotor/hub is at z = 0 and the floor at z = -``HUB_HEIGHT``. Below the
    hub the cells go from ``Z_GROUND_CELL`` (at the ground, for the wall
    function) up to the mesh's hub-adjacent size (``D/32`` coarse, ``D/64``
    fine); above the hub they grow at ``Z_GROWTH`` to ``domain_top``.
    """
    top = float(domain_top)
    if top <= 0.0:
        raise ValueError(f"domain top {top} must be above the hub (z = 0)")
    hub_cell = ROTOR_DIAMETER / MESH_D_OVER.get(mesh, MESH_D_OVER["coarse"])
    breaks = [-HUB_HEIGHT, 0.0, top]
    n_low, grade_low = _geometric_layer(HUB_HEIGHT, Z_GROUND_CELL, hub_cell)
    n_up, grade_up = _growing_layer(top, hub_cell, Z_GROWTH)
    return breaks, [n_low, n_up], [grade_low, grade_up]


def _as_domain(domain: object = None) -> dict[str, float | str]:
    """Accept a domain spec, a mesh name, or ``None`` (the default domain)."""
    if domain is None:
        return domain_spec()
    if isinstance(domain, str):
        return domain_spec(mesh=domain)
    if isinstance(domain, dict):
        return domain
    raise TypeError(f"unsupported domain {domain!r}")


def cell_count(domain: object = None) -> int:
    """Total hexahedral cell count of the domain/mesh."""
    domain = _as_domain(domain)
    total = sum(flow_cells(domain)) * sum(lateral_cells(domain))
    _, z_cells, _ = vertical_mesh(domain["top"], str(domain["mesh"]))
    return total * sum(z_cells)


def hub_cell_size(domain: object = None) -> float:
    """Finest hub-adjacent vertical cell [m]; the time-step constraint length."""
    domain = _as_domain(domain)
    breaks, z_cells, z_grading = vertical_mesh(domain["top"], str(domain["mesh"]))
    hub_adjacent = []
    for index, cells in enumerate(z_cells):
        sizes = _cell_sizes(
            breaks[index + 1] - breaks[index], cells, z_grading[index]
        )
        hub_adjacent.append(sizes[-1] if index == 0 else sizes[0])
    return max(hub_adjacent)


def inflow_fields(speed: float) -> dict[str, float]:
    """k and omega for the configured inflow turbulence intensity."""
    intensity = TURBULENCE_INTENSITY
    length = MIXING_LENGTH_D * ROTOR_DIAMETER
    k = 1.5 * (intensity * float(speed)) ** 2
    c_mu = 0.09
    omega = math.sqrt(k) / (c_mu**0.25 * length)
    return {"k": k, "omega": omega}


def _cell_sizes(length: float, cells: int, grading: float) -> list[float]:
    """OpenFOAM ``simpleGrading`` cell sizes for one block direction."""
    if cells < 1:
        raise ValueError("cells must be positive")
    if cells == 1:
        return [length]
    q = float(grading) ** (1.0 / (cells - 1))
    first = length * (q - 1.0) / (q**cells - 1.0)
    return [first * q**i for i in range(cells)]


# ---------------------------------------------------------------------------
# Dictionary helpers
# ---------------------------------------------------------------------------
def foam_header(object_name: str, klass: str = "dictionary") -> str:
    return f"""/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Website:  www.openfoam.com                      |
|   \\\\  /    A nd           |                                                 |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {klass};
    object      {object_name};
}}
// Generated by tools/generate_case.py. Do not edit by hand.

"""


def foam_vector(values: list[float] | tuple[float, ...]) -> str:
    parts = []
    for value in values:
        number = float(value)
        if number == 0.0:  # normalise -0.0 so the rendered text is stable
            number = 0.0
        parts.append(f"{number:.9g}")
    return "(" + " ".join(parts) + ")"


def render_cell_list(values: list[list[float]], indent: str = "            ") -> str:
    return "\n".join(
        indent + "(" + " ".join(f"{float(value):.9g}" for value in row) + ")"
        for row in values
    )


def turbine_origin() -> tuple[float, float, float]:
    """Rotor centre: the hub at the origin; the floor is z = -``HUB_HEIGHT``."""
    return (0.0, 0.0, 0.0)


def blade_profile_names() -> list[str]:
    """One ``profileData`` name per blade station, keyed by the AeroDyn id.

    The AeroDyn ``BlAFID`` is 1..50; the P1 polar files are ``polar_00`` ..
    ``polar_49`` in station order.
    """
    return [f"polar_{station:02d}" for station in range(50)]


def blade_element_profiles() -> list[str]:
    """``elementProfiles`` in station order.

    ``actuatorLineSource`` maps element ``i`` to
    ``elementProfiles[i*size/nElements]`` (``actuatorLineSource.C:251``), so a
    50-entry list distributes the per-station polars across the 147 elements
    without a family-interpolation step.
    """
    return blade_profile_names()


def blade_element_rows(pitch_deg: float = RATED_PITCH_DEG) -> list[list[float]]:
    """AFTAL blade rows
    ``(axialDistance radius azimuth chord chordMount pitch curveAngle)``.

    Physical along-blade radius (``HubRad + BlSpn``) with ``coneAngle 4``; the
    P0 loader owns the mount, the ``pitch = -(twist + collective)`` sign, the
    prebend (``axialDistance = -BlCrvAC``), the sweep (``azimuth``) and the
    ``BlCrvAng`` section tilt (``curveAngle``). The 7th column is additive: a
    6-column table keeps the legacy zero curve angle.
    """
    return blade_geometry.element_rows(BLADE_CSV, collective_pitch_deg=pitch_deg)


def hub_element_rows() -> list[list[float]]:
    """AFTAL hub rows ``(axialDistance height diameter)`` (7.94 m cylinder)."""
    return [
        [0.0, blade_geometry.HUB_RADIUS, blade_geometry.HUB_DIAMETER],
        [0.0, -blade_geometry.HUB_RADIUS, blade_geometry.HUB_DIAMETER],
    ]


def tower_element_rows() -> list[list[float]]:
    """Tower ALM rows ``(axialDistance height diameter)`` from the WindIO tower.

    ``height`` is along the vertical from the rotor/hub at the origin, so the
    tower is below the hub (negative heights); ``axialDistance`` is the tower's
    downwind offset (``-overhang``, since the rotor axis points upwind). The
    overhang is read from the WindIO nacelle (``drivetrain.overhang``), so the
    tower position is derived from the same geometry source as the blade.
    """
    overhang = blade_geometry.read_tower_overhang()
    return [
        [-overhang, station["z"] - HUB_HEIGHT, station["diameter"]]
        for station in blade_geometry.read_tower_table()
    ]


def tower_drag_coefficient() -> float:
    """Tower drag coefficient from the WindIO tower (AeroDyn ``TwrCd``)."""
    stations = blade_geometry.read_tower_table()
    return stations[0]["cd"] if stations else 1.1


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------
def render_block_mesh(
    domain: object = None,
    flow_axis: str = DEFAULT_FLOW_AXIS,
) -> str:
    """18-block hexahedral blockMeshDict with six far-field patches.

    The mesh roles are x=flow, y=lateral, z=vertical; ``flow_axis`` maps them
    to physical coordinates (see ``_role_to_physical``). The vertical mesh is
    hub-anchored: z = 0 at the rotor, the floor at -``HUB_HEIGHT``.
    """
    domain = _as_domain(domain)
    z_breaks, z_cells, z_grading = vertical_mesh(domain["top"], str(domain["mesh"]))
    breaks = {"x": flow_breaks(domain), "y": lateral_breaks(domain), "z": z_breaks}
    cells = {"x": flow_cells(domain), "y": lateral_cells(domain), "z": z_cells}
    grading = {
        "x": [float(value) for value in BASE_FLOW_GRADING],
        "y": [float(value) for value in BASE_LAT_GRADING],
        "z": z_grading,
    }
    nx, ny, nz = (len(breaks[axis]) for axis in ("x", "y", "z"))

    def vertex(ix: int, iy: int, iz: int) -> int:
        return (iz * ny + iy) * nx + ix

    vertices = []
    for z in breaks["z"]:
        for y in breaks["y"]:
            for x in breaks["x"]:
                px, py, pz = _role_to_physical(flow_axis, x, y, z)
                vertices.append(f"    ({px:.9g} {py:.9g} {pz:.9g})")

    blocks = []
    faces: dict[str, list[str]] = {name: [] for name in PATCH_NAMES}
    for iz in range(nz - 1):
        for iy in range(ny - 1):
            for ix in range(nx - 1):
                v000 = vertex(ix, iy, iz)
                v100 = vertex(ix + 1, iy, iz)
                v110 = vertex(ix + 1, iy + 1, iz)
                v010 = vertex(ix, iy + 1, iz)
                v001 = vertex(ix, iy, iz + 1)
                v101 = vertex(ix + 1, iy, iz + 1)
                v111 = vertex(ix + 1, iy + 1, iz + 1)
                v011 = vertex(ix, iy + 1, iz + 1)
                blocks.append(
                    "    hex "
                    f"({v000} {v100} {v110} {v010} {v001} {v101} {v111} {v011}) "
                    f"({cells['x'][ix]} {cells['y'][iy]} {cells['z'][iz]}) "
                    f"simpleGrading ({grading['x'][ix]:.9g} "
                    f"{grading['y'][iy]:.9g} {grading['z'][iz]:.9g})"
                )
                if ix == 0:
                    faces["inlet"].append(f"            ({v000} {v001} {v011} {v010})")
                if ix == nx - 2:
                    faces["outlet"].append(f"            ({v100} {v110} {v111} {v101})")
                if iz == 0:
                    faces["bottom"].append(f"            ({v000} {v010} {v110} {v100})")
                if iz == nz - 2:
                    faces["top"].append(f"            ({v001} {v101} {v111} {v011})")
                if iy == 0:
                    faces["sideMinus"].append(f"            ({v000} {v100} {v101} {v001})")
                if iy == ny - 2:
                    faces["sidePlus"].append(f"            ({v010} {v011} {v111} {v110})")

    patch_types = {
        "inlet": "patch",
        "outlet": "patch",
        "bottom": "wall",
        "top": "symmetryPlane",
        "sideMinus": "symmetryPlane",
        "sidePlus": "symmetryPlane",
    }

    def patch(name: str) -> str:
        return (
            f"    {name}\n"
            "    {\n"
            f"        type {patch_types[name]};\n"
            "        faces\n"
            "        (\n"
            + "\n".join(faces[name])
            + "\n        );\n"
            "    }"
        )

    return (
        foam_header("blockMeshDict")
        + "scale 1;\n\nvertices\n(\n"
        + "\n".join(vertices)
        + "\n);\n\nblocks\n(\n"
        + "\n".join(blocks)
        + "\n);\n\nedges ();\n\nboundary\n(\n"
        + "\n".join(patch(name) for name in PATCH_NAMES)
        + "\n);\n\nmergePatchPairs ();\n"
    )


def render_toposet(flow_axis: str = DEFAULT_FLOW_AXIS) -> str:
    """One cellSet box enclosing the rotor disk, hub and the 4 deg cone."""
    origin = turbine_origin()
    if flow_axis == "x":
        half = (0.5 * ROTOR_DIAMETER, 1.0 * ROTOR_DIAMETER, 1.0 * ROTOR_DIAMETER)
    else:
        half = (1.0 * ROTOR_DIAMETER, 0.5 * ROTOR_DIAMETER, 1.0 * ROTOR_DIAMETER)
    minimum = tuple(origin[i] - half[i] for i in range(3))
    maximum = tuple(origin[i] + half[i] for i in range(3))
    return foam_header("topoSetDict") + f"""actions
(
    {{
        name turbine;
        type cellSet;
        action new;
        source boxToCell;
        box {foam_vector(minimum)} {foam_vector(maximum)};
    }}
);
"""


def render_control_dict(
    speed: float = RATED_SPEED,
    rpm: float = RATED_RPM,
    domain: object = None,
    end_revs: float = DEFAULT_END_REVOLUTIONS,
    start_from: str = "startTime",
    write_interval_deg: float = WRITE_INTERVAL_DEG,
) -> str:
    domain = _as_domain(domain)
    t_rev = revolution_period(rpm)
    end_time = float(end_revs) * t_rev
    # Write every `write_interval_deg` of rotation, so the wake snapshots are a
    # smooth animation at the natural rotor speed. Binary format keeps each
    # snapshot ~4x smaller than ascii; purgeWrite 0 keeps the full history.
    write_interval = (float(write_interval_deg) / 360.0) * t_rev
    return foam_header("controlDict") + f"""application {APPLICATION};
startFrom {start_from};
startTime 0;
stopAt endTime;
endTime {end_time:.8g};
deltaT {delta_t(domain, rpm):.8g};
writeControl runTime;
writeInterval {write_interval:.8g};
purgeWrite 0;
writeFormat binary;
writePrecision 10;
writeCompression off;
timeFormat general;
timePrecision 8;
runTimeModifiable true;
adjustTimeStep off;

libs
(
    "libturbinesFoam.so"
);
"""


def render_fv_schemes() -> str:
    """Cartesian-mesh schemes; backward ddt, linearUpwind for U."""
    return foam_header("fvSchemes") + """ddtSchemes
{
    default         backward;
}

gradSchemes
{
    default         Gauss linear;
    grad(U)         cellLimited Gauss linear 1;
}

divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div(phi,k)      bounded Gauss upwind;
    div(phi,omega)  bounded Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}

laplacianSchemes
{
    default         Gauss linear orthogonal;
}

interpolationSchemes
{
    default         linear;
}

snGradSchemes
{
    default         orthogonal;
}

wallDist
{
    method          meshWave;
}
"""


def render_fv_solution() -> str:
    """GAMG pressure, smoothSolver for the transported fields."""
    return foam_header("fvSolution") + """solvers
{
    p
    {
        solver          GAMG;
        tolerance       1e-7;
        relTol          0.05;
        smoother        DICGaussSeidel;
        cacheAgglomeration true;
        agglomerator    faceAreaPair;
        mergeLevels     1;
    }

    pFinal
    {
        $p;
        tolerance       1e-8;
        relTol          0;
    }

    "(U|k|omega)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-7;
        relTol          0.05;
    }

    "(U|k|omega)Final"
    {
        $U;
        tolerance       1e-8;
        relTol          0;
    }
}

PIMPLE
{
    momentumPredictor          yes;
    nOuterCorrectors           1;
    nCorrectors                2;
    nNonOrthogonalCorrectors   0;
    pRefCell                   0;
    pRefValue                  0;
}

relaxationFactors
{
    equations
    {
        U       0.9;
        k       0.7;
        omega   0.7;
    }
}
"""


def render_decompose_par(ranks: int = NUMBER_OF_SUBDOMAINS) -> str:
    if int(ranks) < 1:
        raise ValueError("ranks must be a positive integer")
    return foam_header("decomposeParDict") + f"""numberOfSubdomains {int(ranks)};
method scotch;
"""


def render_transport_properties() -> str:
    return foam_header("transportProperties") + f"""transportModel Newtonian;

nu              nu [0 2 -1 0 0 0 0] {KINEMATIC_VISCOSITY:.8g};
"""


def render_turbulence_properties() -> str:
    return foam_header("turbulenceProperties") + f"""simulationType RAS;

RAS
{{
    RASModel {TURBULENCE_MODEL};
    turbulence on;
    printCoeffs on;
}}
"""


def render_field_uniform(
    speed: float, field: str, flow_axis: str = DEFAULT_FLOW_AXIS
) -> str:
    """0.org field dictionaries (uniform inflow, symmetry far field)."""
    velocity = float(speed)
    fields = inflow_fields(speed)
    uin = foam_vector(tuple(velocity * c for c in inflow_direction(flow_axis)))
    far = "        type symmetryPlane;"
    if field == "U":
        dims = "[0 1 -1 0 0 0 0]"
        header = "volVectorField"
        internal = f"uniform {uin}"
        inlet = f"type fixedValue;\n        value uniform {uin};"
        outlet = (
            "type inletOutlet;\n"
            "        inletValue uniform (0 0 0);\n"
            f"        value uniform {uin};"
        )
        ground = "type noSlip;"
    elif field == "p":
        dims = "[0 2 -2 0 0 0 0]"
        header = "volScalarField"
        internal = "uniform 0"
        inlet = "type zeroGradient;"
        outlet = "type fixedValue;\n        value uniform 0;"
        ground = "type zeroGradient;"
    elif field == "k":
        dims = "[0 2 -2 0 0 0 0]"
        header = "volScalarField"
        value = fields["k"]
        internal = f"uniform {value:.8g}"
        inlet = f"type fixedValue;\n        value uniform {value:.8g};"
        outlet = (
            "type inletOutlet;\n"
            "        inletValue uniform 0;\n"
            f"        value uniform {value:.8g};"
        )
        ground = f"type kqRWallFunction;\n        value uniform {value:.8g};"
    elif field == "omega":
        dims = "[0 0 -1 0 0 0 0]"
        header = "volScalarField"
        value = fields["omega"]
        internal = f"uniform {value:.8g}"
        inlet = f"type fixedValue;\n        value uniform {value:.8g};"
        outlet = (
            "type inletOutlet;\n"
            "        inletValue uniform 0;\n"
            f"        value uniform {value:.8g};"
        )
        ground = f"type omegaWallFunction;\n        value uniform {value:.8g};"
    elif field == "nut":
        dims = "[0 2 -1 0 0 0 0]"
        header = "volScalarField"
        internal = "uniform 0"
        inlet = "type fixedValue;\n        value uniform 0;"
        outlet = (
            "type inletOutlet;\n"
            "        inletValue uniform 0;\n"
            "        value uniform 0;"
        )
        ground = "type nutkWallFunction;\n        value uniform 0;"
    else:
        raise ValueError(f"unknown field {field!r}")

    far_block = "    bottom\n    {\n" + ground + "\n    }\n" + "\n".join(
        f"    {name}\n    {{\n{far}\n    }}"
        for name in ("top", "sideMinus", "sidePlus")
    )
    return foam_header(field, header) + f"""dimensions      {dims};

internalField   {internal};

boundaryField
{{
    inlet
    {{
        {inlet}
    }}

    outlet
    {{
        {outlet}
    }}

{far_block}
}}
"""


def render_fv_options(
    speed: float = RATED_SPEED,
    rpm: float = RATED_RPM,
    pitch_deg: float = RATED_PITCH_DEG,
    case_dir: Path = DEFAULT_CASE_DIR,
    n_elements: int = N_ELEMENTS,
    cone_angle: float = PRECONE_DEG,
    flow_axis: str = DEFAULT_FLOW_AXIS,
    tower: bool = True,
    hub: bool = False,
) -> str:
    """The neutral-baseline ``axialFlowTurbineALSource``.

    Three blades 120 deg apart, 147 ALM elements over 49 geometry segments,
    the 50 per-station P1 polars, end effects off and no ``tipCorrection``
    block. No rotational augmentation and no dynamic stall. ``flow_axis``
    selects the rotor-axis/inflow orientation (x = OpenFAST, y = Aeroelast).
    """
    tsr = tip_speed_ratio(speed, rpm)
    origin = turbine_origin()
    axis_vec = rotor_axis(flow_axis)
    free_stream = tuple(float(speed) * c for c in inflow_direction(flow_axis))
    polars = _polars_include_dir(case_dir)
    profiles = " ".join(blade_element_profiles())
    blade_rows = "\n".join(
        "                    ("
        + " ".join(f"{value:.9g}" for value in row)
        + ")"
        for row in blade_element_rows(pitch_deg)
    )
    hub_rows = render_cell_list(hub_element_rows(), indent="                ")
    if hub:
        hub_block = f"""        hub
        {{
            nElements 4;
            elementProfiles (cylinder);
            elementData
            (
{hub_rows}
            );
        }}
"""
    else:
        hub_block = ""
    tower_rows = render_cell_list(tower_element_rows(), indent="                ")
    tower_cd = tower_drag_coefficient()
    if tower:
        tower_block = f"""
        tower
        {{
            // The OpenFAST reference has TwrAero=True, TwrCd={tower_cd:.3g}; the
            // tower is excluded from the rotor total drag (RotThrust is rotor-only).
            includeInTotalDrag false;
            nElements {TOWER_N_ELEMENTS};
            elementProfiles (tower);
            elementData
            (
{tower_rows}
            );
        }}
"""
        tower_profile = (
            f"            tower {{ data ((-180 0 {tower_cd:.8g} 0)"
            f" (180 0 {tower_cd:.8g} 0)); }}"
        )
    else:
        tower_block = ""
        tower_profile = ""
    profile_blocks = "\n".join(
        f"""            {name}
            {{
                GaussianCoeffs
                {{
                    chordFactor 0.25;
                    dragFactor 1.0;
                    meshFactor 1;
                }}
                #include "{polars}/{name}.dat"
            }}"""
        for name in blade_profile_names()
    )
    return foam_header("fvOptions") + f"""turbine
{{
    type axialFlowTurbineALSource;
    active on;

    axialFlowTurbineALSourceCoeffs
    {{
        fieldNames (U);
        selectionMode cellSet;
        cellSet turbine;
        origin {foam_vector(origin)};
        axis {foam_vector(axis_vec)};
        verticalDirection (0 0 1);
        freeStreamVelocity {foam_vector(free_stream)};
        tipSpeedRatio {tsr:.8g};
        rotorRadius {ROTOR_RADIUS:.8g};
        azimuthalOffset 0;
        coneAngle {float(cone_angle):.8g};

        dynamicStall
        {{
            active off;
            dynamicStallModel LeishmanBeddoes;
        }}

        rotationalAugmentation
        {{
            active off;
            model DuSelig;
            a 1;
            b 1;
            d 1;
        }}

        endEffects
        {{
            active off;
            endEffectsModel Glauert;
            GlauertCoeffs
            {{
                tipEffects off;
                rootEffects off;
            }}
        }}

        blades
        {{
            blade1
            {{
                writePerf true;
                writeElementPerf true;
                elementType actuatorLineElement;
                nElements {int(n_elements)};
                elementProfiles
                (
                    {profiles}
                );
                elementData
                (
{blade_rows}
                );
            }}
            blade2
            {{
                $blade1;
                writePerf false;
                writeElementPerf false;
                azimuthalOffset 120;
            }}
            blade3
            {{
                $blade1;
                writePerf false;
                writeElementPerf false;
                azimuthalOffset 240;
            }}
        }}

{hub_block}{tower_block}        profileData
        {{
{profile_blocks}
            cylinder {{ data ((-180 0 1.1 0) (180 0 1.1 0)); }}
{tower_profile}
        }}
    }}
}}
"""


def _polars_include_dir(case_dir: Path) -> str:
    """Path to ``data/polars`` relative to the rendered ``case/system`` dir."""
    return Path(os.path.relpath(POLARS_DIR, Path(case_dir) / "system")).as_posix()


def outputs(
    speed: float = RATED_SPEED,
    rpm: float = RATED_RPM,
    pitch_deg: float = RATED_PITCH_DEG,
    domain: object = None,
    case_dir: Path = DEFAULT_CASE_DIR,
    n_elements: int = N_ELEMENTS,
    cone_angle: float = PRECONE_DEG,
    end_revs: float = DEFAULT_END_REVOLUTIONS,
    start_from: str = "startTime",
    flow_axis: str = DEFAULT_FLOW_AXIS,
    tower: bool = True,
    hub: bool = False,
    ranks: int = NUMBER_OF_SUBDOMAINS,
    write_interval_deg: float = WRITE_INTERVAL_DEG,
) -> dict[Path, str]:
    domain = _as_domain(domain)
    case_dir = Path(case_dir)
    system = case_dir / "system"
    constant = case_dir / "constant"
    zero = case_dir / "0.org"
    rendered: dict[Path, str] = {
        system / "blockMeshDict": render_block_mesh(domain, flow_axis),
        system / "topoSetDict": render_toposet(flow_axis),
        system / "controlDict": render_control_dict(
            speed, rpm, domain, end_revs, start_from, write_interval_deg
        ),
        system / "decomposeParDict": render_decompose_par(ranks),
        system / "fvSchemes": render_fv_schemes(),
        system / "fvSolution": render_fv_solution(),
        system / "fvOptions": render_fv_options(
            speed,
            rpm,
            pitch_deg,
            case_dir,
            n_elements,
            cone_angle,
            flow_axis,
            tower,
            hub,
        ),
        constant / "transportProperties": render_transport_properties(),
        constant / "turbulenceProperties": render_turbulence_properties(),
    }
    for field in ("U", "p", "k", "omega", "nut"):
        rendered[zero / field] = render_field_uniform(speed, field, flow_axis)
    return rendered


def check_outputs(rendered: dict[Path, str], case_dir: Path) -> bool:
    clean = True
    for path, expected in rendered.items():
        if not path.exists():
            print(f"missing generated file: {_display(path, case_dir)}", file=sys.stderr)
            clean = False
            continue
        current = path.read_text(encoding="utf-8")
        if current != expected:
            print(f"stale generated file: {_display(path, case_dir)}", file=sys.stderr)
            diff = difflib.unified_diff(
                current.splitlines(),
                expected.splitlines(),
                fromfile="current",
                tofile="expected",
                n=2,
            )
            print("\n".join(list(diff)[:40]), file=sys.stderr)
            clean = False
    return clean


def _display(path: Path, case_dir: Path) -> str:
    try:
        return str(path.relative_to(case_dir))
    except ValueError:
        return str(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--speed", type=float, default=RATED_SPEED)
    parser.add_argument("--rpm", type=float, default=RATED_RPM)
    parser.add_argument("--pitch", type=float, default=RATED_PITCH_DEG)
    parser.add_argument("--mesh", choices=MESH_CHOICES, default="coarse")
    parser.add_argument("--n-elements", type=int, default=N_ELEMENTS)
    parser.add_argument("--cone-angle", type=float, default=PRECONE_DEG)
    parser.add_argument("--end-revs", type=float, default=DEFAULT_END_REVOLUTIONS)
    parser.add_argument(
        "--start-from",
        choices=("startTime", "latestTime"),
        default="startTime",
        help="controlDict startFrom; use latestTime to resume a decomposed run",
    )
    parser.add_argument(
        "--flow-axis",
        choices=FLOW_AXIS_CHOICES,
        default=DEFAULT_FLOW_AXIS,
        help="flow/rotor axis: y = Aeroelast/FSI (fluid +Y, default), x = OpenFAST",
    )
    parser.add_argument(
        "--domain-upstream",
        type=float,
        default=DEFAULT_UPSTREAM_D,
        help="upstream extent [rotor diameters]",
    )
    parser.add_argument(
        "--domain-downstream",
        type=float,
        default=DEFAULT_DOWNSTREAM_D,
        help="downstream extent [rotor diameters]",
    )
    parser.add_argument(
        "--domain-lateral",
        type=float,
        default=DEFAULT_LATERAL_D,
        help="lateral half-extent [rotor diameters]",
    )
    parser.add_argument(
        "--domain-fine-max",
        type=float,
        default=DEFAULT_FINE_MAX_D,
        help="downstream end of the refined region [rotor diameters]",
    )
    parser.add_argument(
        "--domain-fine-lat",
        type=float,
        default=DEFAULT_FINE_LAT_D,
        help="lateral half-width of the refined region [rotor diameters]",
    )
    parser.add_argument(
        "--domain-top",
        type=float,
        default=DEFAULT_DOMAIN_TOP,
        help="domain top [m] above the rotor (the floor is at -hub height)",
    )
    parser.add_argument(
        "--tower",
        choices=("on", "off"),
        default="on",
        help="include the tower ALM (from the WindIO tower; default on, like OpenFAST)",
    )
    parser.add_argument(
        "--hub",
        choices=("on", "off"),
        default="off",
        help="include the hub drag body; default off (AeroDyn has no hub aero)",
    )
    parser.add_argument(
        "--ranks",
        type=int,
        default=NUMBER_OF_SUBDOMAINS,
        help="numberOfSubdomains in decomposeParDict (must match --ntasks)",
    )
    parser.add_argument(
        "--write-interval-deg",
        type=float,
        default=WRITE_INTERVAL_DEG,
        help="wake snapshot every N degrees of rotation (writeInterval = N/360 * T_rev)",
    )
    parser.add_argument("--case-dir", type=Path, default=DEFAULT_CASE_DIR)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail (exit 1) if generated files are missing or stale; never writes",
    )
    args = parser.parse_args(argv)

    try:
        domain = domain_spec(
            args.mesh,
            args.domain_upstream,
            args.domain_downstream,
            args.domain_lateral,
            args.domain_fine_max,
            args.domain_fine_lat,
            args.domain_top,
        )
        rendered = outputs(
            args.speed,
            args.rpm,
            args.pitch,
            domain,
            args.case_dir,
            args.n_elements,
            args.cone_angle,
            args.end_revs,
            args.start_from,
            args.flow_axis,
            args.tower == "on",
            args.hub == "on",
            args.ranks,
            args.write_interval_deg,
        )
    except (KeyError, ValueError) as exc:
        print(f"case generation error: {exc}", file=sys.stderr)
        return 2

    if args.check:
        return 0 if check_outputs(rendered, Path(args.case_dir)) else 1

    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(_display(path, PACKAGE))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
