#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
"""Render the IEA 15-240-RWT rated-point case from the committed P0/P1 data.

The case skeleton mirrors the NREL Phase VI uniform-inflow case
(``validation/phaseVI/tools/generate_case.py``) scaled to the 15 MW rotor:
an 18-block hexahedral far-field box, the same boundary layout, the same
URANS solver/schemes and an ``axialFlowTurbineALSource`` neutral baseline.

Sources of truth (never edited here):

- ``data/iea15mw_blade.csv`` (P0) — chord, twist, chord mount and the ALM
  mounting angle for all 50 stations.
- ``data/polars/polar_NN.dat`` (P1) — one ``profileData`` polar per station.

Operating point (rated, below the rated wind speed of the reference):
``V = 10.659 m/s``, ``Omega = 7.518 rpm``, collective pitch ``0``.  The tip
speed ratio is *computed* as ``Omega*R/V`` with the P0 projected radius
``R = 120.67532316 m`` — it is not a guessed constant.

Precone decision (option b): the ``elementData`` radius column is the
*physical* along-blade radius (``HubRad + BlSpn``, tip 120.9699 m) and the
rotor is rendered with ``coneAngle 4``.  ``axialFlowTurbineALSource``
supports the cone directly (``coneAngle`` is a documented
``lookupOrDefault`` key, ``axialFlowTurbineALSource.C:83``), so the extra key
is the only cost, and it preserves the real blade geometry while the
projected tip lands exactly on ``rotorRadius``:
``120.9699*cos(4 deg) = 120.6753 m``.

Every generated file carries a "Generated by tools/generate_case.py" banner;
``--check`` re-renders in memory and fails when a file on disk is missing or
stale, without writing anything.

Usage:
    generate_case.py [--speed 10.659] [--rpm 7.518] [--pitch 0]
                     [--mesh coarse] [--n-elements 147] [--cone-angle 4]
                     [--end-revs 3] [--case-dir DIR] [--check]
"""

from __future__ import annotations

import argparse
import difflib
import math
import os
import sys
from pathlib import Path
from typing import Any

TOOLS_DIR = Path(__file__).resolve().parent
PACKAGE = TOOLS_DIR.parent
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

import blade_geometry  # noqa: E402

#: Committed P0/P1 inputs.
BLADE_CSV = PACKAGE / "data" / "iea15mw_blade.csv"
POLARS_DIR = PACKAGE / "data" / "polars"
DEFAULT_CASE_DIR = PACKAGE / "case"

# --- Rated operating point (NREL/TP-5000-75698 Table 3-1) --------------------
RATED_SPEED = 10.659
RATED_RPM = 7.518
RATED_PITCH_DEG = 0.0

# --- Rotor geometry (P0 radius decision) -------------------------------------
ROTOR_RADIUS = blade_geometry.ROTOR_RADIUS_PUBLISHED
ROTOR_DIAMETER = 2.0 * ROTOR_RADIUS
HUB_HEIGHT = 150.0
N_BLADES = 3
#: 50 geometry stations -> 49 segments; 147 = 3 elements per segment.
N_ELEMENTS = 147
#: 4 deg precone, applied through the source's `coneAngle` key (option b).
PRECONE_DEG = 4.0

# --- Domain and mesh (Phase VI D-normalised box, D/32) -----------------------
#: Box 20D x 8D x 5D around the rotor, hub height 150 m.
DOMAIN_D = {"x": (-5.0, 15.0), "y": (-4.0, 4.0), "z_offset": (-2.5, 2.5)}
MESH_CHOICES = ("coarse",)
#: Block breaks in D units (x/y absolute D; z hub offset in D).
BREAKS_D = {
    "x": [-5.0, -0.5, 8.0, 15.0],
    "y": [-4.0, -1.5, 1.5, 4.0],
    "z": [-2.5, 0.0, 2.5],
}
#: D/32 development mesh; identical relative resolution to Phase VI coarse.
MESH = {
    "coarse": {
        "x": {"cells": [50, 272, 60], "grading": [0.160029, 1.0, 9.252929]},
        "y": {"cells": [36, 96, 36], "grading": [0.241240, 1.0, 4.145249]},
        "z": {"cells": [52, 52], "grading": [0.4464, 2.2404]},
        "delta_t": 0.075,
    }
}
#: Recorded expected cell count of the D/32 mesh (Phase VI-identical topology).
EXPECTED_CELL_COUNT = 6_674_304

# --- Decomposition (P3 plan) -------------------------------------------------
NUMBER_OF_SUBDOMAINS = 48

# --- Solver / inflow ---------------------------------------------------------
APPLICATION = "pimpleFoam"
TURBULENCE_MODEL = "kOmegaSST"
KINEMATIC_VISCOSITY = 1.5e-5
TURBULENCE_INTENSITY = 0.005
MIXING_LENGTH_D = 0.07
DEFAULT_END_REVOLUTIONS = 3
WRITE_INTERVAL_REV = 0.5

PATCH_NAMES = ("inlet", "outlet", "bottom", "top", "sideMinus", "sidePlus")


# ---------------------------------------------------------------------------
# Derived kinematics
# ---------------------------------------------------------------------------
def omega_from_rpm(rpm: float) -> float:
    """Rotor angular velocity [rad/s] from a shaft speed in rpm."""
    return float(rpm) * 2.0 * math.pi / 60.0


def tip_speed_ratio(speed: float, rpm: float, radius: float = ROTOR_RADIUS) -> float:
    """Tip speed ratio ``Omega*R/V`` from the operating point.

    Never hard-coded: the readiness note's proposed 9.0786 corresponds to
    7.6575 rpm, not the rated 7.518 rpm, so it is not reproduced here.
    """
    return omega_from_rpm(rpm) * float(radius) / float(speed)


def revolution_period(rpm: float) -> float:
    """One rotor revolution [s]."""
    return 2.0 * math.pi / omega_from_rpm(rpm)


def axis_extents(axis: str) -> list[float]:
    """Physical block extents [m] of one axis (x/y absolute D, z hub offset)."""
    values = [float(value) for value in BREAKS_D[axis]]
    if axis == "z":
        return [HUB_HEIGHT + ROTOR_DIAMETER * value for value in values]
    return [ROTOR_DIAMETER * value for value in values]


def cell_count(mesh: str = "coarse") -> int:
    """Total hexahedral cell count of a rendered mesh."""
    resolution = _resolution(mesh)
    total = 1
    for axis in ("x", "y", "z"):
        total *= sum(int(value) for value in resolution[axis]["cells"])
    return total


def hub_cell_size(mesh: str = "coarse") -> float:
    """Finest (hub-adjacent) z cell [m]; the time-step constraint length."""
    resolution = _resolution(mesh)
    extents = axis_extents("z")
    z_cells = [int(value) for value in resolution["z"]["cells"]]
    z_grading = [float(value) for value in resolution["z"]["grading"]]
    hub_adjacent = []
    for index, cells in enumerate(z_cells):
        sizes = _cell_sizes(
            extents[index + 1] - extents[index], cells, z_grading[index]
        )
        hub_adjacent.append(sizes[-1] if index == 0 else sizes[0])
    return max(hub_adjacent)


def inflow_fields(speed: float) -> dict[str, float]:
    """k and omega for the configured inflow turbulence intensity."""
    intensity = TURBULENCE_INTENSITY
    length = MIXING_LENGTH_D * ROTOR_DIAMETER
    k = 1.5 * (intensity * float(speed)) ** 2
    c_mu = 0.09
    omega = math.sqrt(k) / (c_mu**0.25 * length)
    return {"k": k, "omega": omega}


def _resolution(mesh: str) -> dict[str, Any]:
    if mesh not in MESH:
        raise KeyError(
            f"unsupported mesh resolution {mesh!r}; choose from {sorted(MESH)}"
        )
    return MESH[mesh]


def _cell_sizes(length: float, cells: int, grading: float) -> list[float]:
    """OpenFOAM ``simpleGrading`` cell sizes for one block direction."""
    if cells < 1:
        raise ValueError("cells must be positive")
    if cells == 1:
        return [length]
    q = float(grading) ** (1.0 / (cells - 1))
    first = length * (q - 1.0) / (q**cells - 1.0)
    return [first * q**i for i in range(cells)]


# ---------------------------------------------------------------------------
# Dictionary helpers
# ---------------------------------------------------------------------------
def foam_header(object_name: str, klass: str = "dictionary") -> str:
    return f"""/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox           |
|  \\\\    /   O peration     | Website:  www.openfoam.com                      |
|   \\\\  /    A nd           |                                                 |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
FoamFile
{{
    version     2.0;
    format      ascii;
    class       {klass};
    object      {object_name};
}}
// Generated by tools/generate_case.py. Do not edit by hand.

"""


def foam_vector(values: list[float] | tuple[float, ...]) -> str:
    return "(" + " ".join(f"{float(value):.9g}" for value in values) + ")"


def render_cell_list(values: list[list[float]], indent: str = "            ") -> str:
    return "\n".join(
        indent + "(" + " ".join(f"{float(value):.9g}" for value in row) + ")"
        for row in values
    )


def turbine_origin() -> tuple[float, float, float]:
    """Rotor centre in mesh coordinates: the hub at x = y = 0, z = hub height."""
    return (0.0, 0.0, HUB_HEIGHT)


def blade_profile_names() -> list[str]:
    """One ``profileData`` name per blade station, keyed by the AeroDyn id.

    The AeroDyn ``BlAFID`` is 1..50; the P1 polar files are ``polar_00`` ..
    ``polar_49`` in station order.
    """
    return [f"polar_{station:02d}" for station in range(50)]


def blade_element_profiles() -> list[str]:
    """``elementProfiles`` in station order.

    ``actuatorLineSource`` maps element ``i`` to
    ``elementProfiles[i*size/nElements]`` (``actuatorLineSource.C:251``), so a
    50-entry list distributes the per-station polars across the 147 elements
    without a family-interpolation step.
    """
    return blade_profile_names()


def blade_element_rows(pitch_deg: float = RATED_PITCH_DEG) -> list[list[float]]:
    """AFTAL blade rows ``(axialDistance radius azimuth chord chordMount pitch)``.

    Physical along-blade radius (``HubRad + BlSpn``) with ``coneAngle 4``; the
    P0 loader owns the mount and the ``pitch = -(twist + collective)`` sign.
    """
    return blade_geometry.element_rows(BLADE_CSV, collective_pitch_deg=pitch_deg)


def hub_element_rows() -> list[list[float]]:
    """AFTAL hub rows ``(axialDistance height diameter)`` (7.94 m cylinder)."""
    return [
        [0.0, blade_geometry.HUB_RADIUS, blade_geometry.HUB_DIAMETER],
        [0.0, -blade_geometry.HUB_RADIUS, blade_geometry.HUB_DIAMETER],
    ]


# ---------------------------------------------------------------------------
# Renderers
# ---------------------------------------------------------------------------
def render_block_mesh(mesh: str = "coarse") -> str:
    """18-block hexahedral blockMeshDict with six far-field patches."""
    resolution = _resolution(mesh)
    breaks = {axis: axis_extents(axis) for axis in ("x", "y", "z")}
    cells = {
        axis: [int(value) for value in resolution[axis]["cells"]]
        for axis in ("x", "y", "z")
    }
    grading = {
        axis: [float(value) for value in resolution[axis]["grading"]]
        for axis in ("x", "y", "z")
    }
    nx, ny, nz = (len(breaks[axis]) for axis in ("x", "y", "z"))

    def vertex(ix: int, iy: int, iz: int) -> int:
        return (iz * ny + iy) * nx + ix

    vertices = []
    for z in breaks["z"]:
        for y in breaks["y"]:
            for x in breaks["x"]:
                vertices.append(f"    ({x:.9g} {y:.9g} {z:.9g})")

    blocks = []
    faces: dict[str, list[str]] = {name: [] for name in PATCH_NAMES}
    for iz in range(nz - 1):
        for iy in range(ny - 1):
            for ix in range(nx - 1):
                v000 = vertex(ix, iy, iz)
                v100 = vertex(ix + 1, iy, iz)
                v110 = vertex(ix + 1, iy + 1, iz)
                v010 = vertex(ix, iy + 1, iz)
                v001 = vertex(ix, iy, iz + 1)
                v101 = vertex(ix + 1, iy, iz + 1)
                v111 = vertex(ix + 1, iy + 1, iz + 1)
                v011 = vertex(ix, iy + 1, iz + 1)
                blocks.append(
                    "    hex "
                    f"({v000} {v100} {v110} {v010} {v001} {v101} {v111} {v011}) "
                    f"({cells['x'][ix]} {cells['y'][iy]} {cells['z'][iz]}) "
                    f"simpleGrading ({grading['x'][ix]:.9g} "
                    f"{grading['y'][iy]:.9g} {grading['z'][iz]:.9g})"
                )
                if ix == 0:
                    faces["inlet"].append(f"            ({v000} {v001} {v011} {v010})")
                if ix == nx - 2:
                    faces["outlet"].append(f"            ({v100} {v110} {v111} {v101})")
                if iz == 0:
                    faces["bottom"].append(f"            ({v000} {v010} {v110} {v100})")
                if iz == nz - 2:
                    faces["top"].append(f"            ({v001} {v101} {v111} {v011})")
                if iy == 0:
                    faces["sideMinus"].append(f"            ({v000} {v100} {v101} {v001})")
                if iy == ny - 2:
                    faces["sidePlus"].append(f"            ({v010} {v011} {v111} {v110})")

    patch_types = {
        "inlet": "patch",
        "outlet": "patch",
        "bottom": "symmetryPlane",
        "top": "symmetryPlane",
        "sideMinus": "symmetryPlane",
        "sidePlus": "symmetryPlane",
    }

    def patch(name: str) -> str:
        return (
            f"    {name}\n"
            "    {\n"
            f"        type {patch_types[name]};\n"
            "        faces\n"
            "        (\n"
            + "\n".join(faces[name])
            + "\n        );\n"
            "    }"
        )

    return (
        foam_header("blockMeshDict")
        + "scale 1;\n\nvertices\n(\n"
        + "\n".join(vertices)
        + "\n);\n\nblocks\n(\n"
        + "\n".join(blocks)
        + "\n);\n\nedges ();\n\nboundary\n(\n"
        + "\n".join(patch(name) for name in PATCH_NAMES)
        + "\n);\n\nmergePatchPairs ();\n"
    )


def render_toposet() -> str:
    """One cellSet box enclosing the rotor disk, hub and the 4 deg cone."""
    origin = turbine_origin()
    minimum = (
        origin[0] - 0.5 * ROTOR_DIAMETER,
        origin[1] - 1.0 * ROTOR_DIAMETER,
        origin[2] - 1.0 * ROTOR_DIAMETER,
    )
    maximum = (
        origin[0] + 0.5 * ROTOR_DIAMETER,
        origin[1] + 1.0 * ROTOR_DIAMETER,
        origin[2] + 1.0 * ROTOR_DIAMETER,
    )
    return foam_header("topoSetDict") + f"""actions
(
    {{
        name turbine;
        type cellSet;
        action new;
        source boxToCell;
        box {foam_vector(minimum)} {foam_vector(maximum)};
    }}
);
"""


def render_control_dict(
    speed: float = RATED_SPEED,
    rpm: float = RATED_RPM,
    mesh: str = "coarse",
    end_revs: float = DEFAULT_END_REVOLUTIONS,
) -> str:
    resolution = _resolution(mesh)
    t_rev = revolution_period(rpm)
    end_time = float(end_revs) * t_rev
    write_interval = WRITE_INTERVAL_REV * t_rev
    return foam_header("controlDict") + f"""application {APPLICATION};
startFrom startTime;
startTime 0;
stopAt endTime;
endTime {end_time:.8g};
deltaT {float(resolution['delta_t']):.8g};
writeControl runTime;
writeInterval {write_interval:.8g};
purgeWrite 1;
writeFormat ascii;
writePrecision 10;
writeCompression off;
timeFormat general;
timePrecision 8;
runTimeModifiable true;
adjustTimeStep off;

libs
(
    "libturbinesFoam.so"
);
"""


def render_fv_schemes() -> str:
    """Cartesian-mesh schemes; backward ddt, linearUpwind for U."""
    return foam_header("fvSchemes") + """ddtSchemes
{
    default         backward;
}

gradSchemes
{
    default         Gauss linear;
    grad(U)         cellLimited Gauss linear 1;
}

divSchemes
{
    default         none;
    div(phi,U)      bounded Gauss linearUpwind grad(U);
    div(phi,k)      bounded Gauss upwind;
    div(phi,omega)  bounded Gauss upwind;
    div((nuEff*dev2(T(grad(U))))) Gauss linear;
}

laplacianSchemes
{
    default         Gauss linear orthogonal;
}

interpolationSchemes
{
    default         linear;
}

snGradSchemes
{
    default         orthogonal;
}

wallDist
{
    method          meshWave;
}
"""


def render_fv_solution() -> str:
    """GAMG pressure, smoothSolver for the transported fields."""
    return foam_header("fvSolution") + """solvers
{
    p
    {
        solver          GAMG;
        tolerance       1e-7;
        relTol          0.05;
        smoother        DICGaussSeidel;
        cacheAgglomeration true;
        agglomerator    faceAreaPair;
        mergeLevels     1;
    }

    pFinal
    {
        $p;
        tolerance       1e-8;
        relTol          0;
    }

    "(U|k|omega)"
    {
        solver          smoothSolver;
        smoother        symGaussSeidel;
        tolerance       1e-7;
        relTol          0.05;
    }

    "(U|k|omega)Final"
    {
        $U;
        tolerance       1e-8;
        relTol          0;
    }
}

PIMPLE
{
    momentumPredictor          yes;
    nOuterCorrectors           1;
    nCorrectors                2;
    nNonOrthogonalCorrectors   0;
    pRefCell                   0;
    pRefValue                  0;
}

relaxationFactors
{
    equations
    {
        U       0.9;
        k       0.7;
        omega   0.7;
    }
}
"""


def render_decompose_par() -> str:
    return foam_header("decomposeParDict") + f"""numberOfSubdomains {NUMBER_OF_SUBDOMAINS};
method scotch;
"""


def render_transport_properties() -> str:
    return foam_header("transportProperties") + f"""transportModel Newtonian;

nu              nu [0 2 -1 0 0 0 0] {KINEMATIC_VISCOSITY:.8g};
"""


def render_turbulence_properties() -> str:
    return foam_header("turbulenceProperties") + f"""simulationType RAS;

RAS
{{
    RASModel {TURBULENCE_MODEL};
    turbulence on;
    printCoeffs on;
}}
"""


def render_field_uniform(speed: float, field: str) -> str:
    """0.org field dictionaries (uniform inflow, symmetry far field)."""
    velocity = float(speed)
    fields = inflow_fields(speed)
    far = "        type symmetryPlane;"
    if field == "U":
        dims = "[0 1 -1 0 0 0 0]"
        header = "volVectorField"
        internal = f"uniform ({velocity:.8g} 0 0)"
        inlet = f"type fixedValue;\n        value uniform ({velocity:.8g} 0 0);"
        outlet = (
            "type inletOutlet;\n"
            "        inletValue uniform (0 0 0);\n"
            f"        value uniform ({velocity:.8g} 0 0);"
        )
    elif field == "p":
        dims = "[0 2 -2 0 0 0 0]"
        header = "volScalarField"
        internal = "uniform 0"
        inlet = "type zeroGradient;"
        outlet = "type fixedValue;\n        value uniform 0;"
    elif field == "k":
        dims = "[0 2 -2 0 0 0 0]"
        header = "volScalarField"
        value = fields["k"]
        internal = f"uniform {value:.8g}"
        inlet = f"type fixedValue;\n        value uniform {value:.8g};"
        outlet = (
            "type inletOutlet;\n"
            "        inletValue uniform 0;\n"
            f"        value uniform {value:.8g};"
        )
    elif field == "omega":
        dims = "[0 0 -1 0 0 0 0]"
        header = "volScalarField"
        value = fields["omega"]
        internal = f"uniform {value:.8g}"
        inlet = f"type fixedValue;\n        value uniform {value:.8g};"
        outlet = (
            "type inletOutlet;\n"
            "        inletValue uniform 0;\n"
            f"        value uniform {value:.8g};"
        )
    elif field == "nut":
        dims = "[0 2 -1 0 0 0 0]"
        header = "volScalarField"
        internal = "uniform 0"
        inlet = "type fixedValue;\n        value uniform 0;"
        outlet = (
            "type inletOutlet;\n"
            "        inletValue uniform 0;\n"
            "        value uniform 0;"
        )
    else:
        raise ValueError(f"unknown field {field!r}")

    far_block = "\n".join(
        f"    {name}\n    {{\n{far}\n    }}"
        for name in ("bottom", "top", "sideMinus", "sidePlus")
    )
    return foam_header(field, header) + f"""dimensions      {dims};

internalField   {internal};

boundaryField
{{
    inlet
    {{
        {inlet}
    }}

    outlet
    {{
        {outlet}
    }}

{far_block}
}}
"""


def render_fv_options(
    speed: float = RATED_SPEED,
    rpm: float = RATED_RPM,
    pitch_deg: float = RATED_PITCH_DEG,
    case_dir: Path = DEFAULT_CASE_DIR,
    n_elements: int = N_ELEMENTS,
    cone_angle: float = PRECONE_DEG,
) -> str:
    """The neutral-baseline ``axialFlowTurbineALSource``.

    Three blades 120 deg apart, 147 ALM elements over 49 geometry segments,
    the 50 per-station P1 polars, end effects off and no ``tipCorrection``
    block. No rotational augmentation and no dynamic stall.
    """
    tsr = tip_speed_ratio(speed, rpm)
    origin = turbine_origin()
    polars = _polars_include_dir(case_dir)
    profiles = " ".join(blade_element_profiles())
    blade_rows = "\n".join(
        "                    ("
        + " ".join(f"{value:.9g}" for value in row)
        + ")"
        for row in blade_element_rows(pitch_deg)
    )
    hub_rows = render_cell_list(hub_element_rows(), indent="                ")
    profile_blocks = "\n".join(
        f"""            {name}
            {{
                GaussianCoeffs
                {{
                    chordFactor 0.25;
                    dragFactor 1.0;
                    meshFactor 1;
                }}
                #include "{polars}/{name}.dat"
            }}"""
        for name in blade_profile_names()
    )
    return foam_header("fvOptions") + f"""turbine
{{
    type axialFlowTurbineALSource;
    active on;

    axialFlowTurbineALSourceCoeffs
    {{
        fieldNames (U);
        selectionMode cellSet;
        cellSet turbine;
        origin {foam_vector(origin)};
        axis (-1 0 0);
        verticalDirection (0 0 1);
        freeStreamVelocity ({float(speed):.8g} 0 0);
        tipSpeedRatio {tsr:.8g};
        rotorRadius {ROTOR_RADIUS:.8g};
        azimuthalOffset 0;
        coneAngle {float(cone_angle):.8g};

        dynamicStall
        {{
            active off;
            dynamicStallModel LeishmanBeddoes;
        }}

        rotationalAugmentation
        {{
            active off;
            model DuSelig;
            a 1;
            b 1;
            d 1;
        }}

        endEffects
        {{
            active off;
            endEffectsModel Glauert;
            GlauertCoeffs
            {{
                tipEffects off;
                rootEffects off;
            }}
        }}

        blades
        {{
            blade1
            {{
                writePerf true;
                writeElementPerf true;
                elementType actuatorLineElement;
                nElements {int(n_elements)};
                elementProfiles
                (
                    {profiles}
                );
                elementData
                (
{blade_rows}
                );
            }}
            blade2
            {{
                $blade1;
                writePerf false;
                writeElementPerf false;
                azimuthalOffset 120;
            }}
            blade3
            {{
                $blade1;
                writePerf false;
                writeElementPerf false;
                azimuthalOffset 240;
            }}
        }}

        hub
        {{
            nElements 4;
            elementProfiles (cylinder);
            elementData
            (
{hub_rows}
            );
        }}

        profileData
        {{
{profile_blocks}
            cylinder {{ data ((-180 0 1.1 0) (180 0 1.1 0)); }}
        }}
    }}
}}
"""


def _polars_include_dir(case_dir: Path) -> str:
    """Path to ``data/polars`` relative to the rendered ``case/system`` dir."""
    return Path(os.path.relpath(POLARS_DIR, Path(case_dir) / "system")).as_posix()


def outputs(
    speed: float = RATED_SPEED,
    rpm: float = RATED_RPM,
    pitch_deg: float = RATED_PITCH_DEG,
    mesh: str = "coarse",
    case_dir: Path = DEFAULT_CASE_DIR,
    n_elements: int = N_ELEMENTS,
    cone_angle: float = PRECONE_DEG,
    end_revs: float = DEFAULT_END_REVOLUTIONS,
) -> dict[Path, str]:
    case_dir = Path(case_dir)
    system = case_dir / "system"
    constant = case_dir / "constant"
    zero = case_dir / "0.org"
    rendered: dict[Path, str] = {
        system / "blockMeshDict": render_block_mesh(mesh),
        system / "topoSetDict": render_toposet(),
        system / "controlDict": render_control_dict(speed, rpm, mesh, end_revs),
        system / "decomposeParDict": render_decompose_par(),
        system / "fvSchemes": render_fv_schemes(),
        system / "fvSolution": render_fv_solution(),
        system / "fvOptions": render_fv_options(
            speed, rpm, pitch_deg, case_dir, n_elements, cone_angle
        ),
        constant / "transportProperties": render_transport_properties(),
        constant / "turbulenceProperties": render_turbulence_properties(),
    }
    for field in ("U", "p", "k", "omega", "nut"):
        rendered[zero / field] = render_field_uniform(speed, field)
    return rendered


def check_outputs(rendered: dict[Path, str], case_dir: Path) -> bool:
    clean = True
    for path, expected in rendered.items():
        if not path.exists():
            print(f"missing generated file: {_display(path, case_dir)}", file=sys.stderr)
            clean = False
            continue
        current = path.read_text(encoding="utf-8")
        if current != expected:
            print(f"stale generated file: {_display(path, case_dir)}", file=sys.stderr)
            diff = difflib.unified_diff(
                current.splitlines(),
                expected.splitlines(),
                fromfile="current",
                tofile="expected",
                n=2,
            )
            print("\n".join(list(diff)[:40]), file=sys.stderr)
            clean = False
    return clean


def _display(path: Path, case_dir: Path) -> str:
    try:
        return str(path.relative_to(case_dir))
    except ValueError:
        return str(path)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--speed", type=float, default=RATED_SPEED)
    parser.add_argument("--rpm", type=float, default=RATED_RPM)
    parser.add_argument("--pitch", type=float, default=RATED_PITCH_DEG)
    parser.add_argument("--mesh", choices=MESH_CHOICES, default="coarse")
    parser.add_argument("--n-elements", type=int, default=N_ELEMENTS)
    parser.add_argument("--cone-angle", type=float, default=PRECONE_DEG)
    parser.add_argument("--end-revs", type=float, default=DEFAULT_END_REVOLUTIONS)
    parser.add_argument("--case-dir", type=Path, default=DEFAULT_CASE_DIR)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail (exit 1) if generated files are missing or stale; never writes",
    )
    args = parser.parse_args(argv)

    try:
        rendered = outputs(
            args.speed,
            args.rpm,
            args.pitch,
            args.mesh,
            args.case_dir,
            args.n_elements,
            args.cone_angle,
            args.end_revs,
        )
    except (KeyError, ValueError) as exc:
        print(f"case generation error: {exc}", file=sys.stderr)
        return 2

    if args.check:
        return 0 if check_outputs(rendered, Path(args.case_dir)) else 1

    for path, content in rendered.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        print(_display(path, PACKAGE))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
