#!/usr/bin/env bash
# Minimal one-blade axialFlowTurbineALSource case for the Dag & Sorensen
# tip-correction tests. The args are:
#   $1: fvOptions variant to install: -on | -off | -axisdown | -axisdown-on |
#       -badmodel (default: none)
#   $2: `-parallel` or nothing
#
# The variant is copied over system/fvOptions inside the run directory; the
# test suite always runs on a throwaway copy of the case, so the committed
# system/fvOptions (the tip-correction-off default) is never modified.

cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

case "$1" in
    -on)
        cp system/fvOptions.on system/fvOptions
        shift
        ;;
    -off)
        cp system/fvOptions.off system/fvOptions
        shift
        ;;
    -badmodel)
        cp system/fvOptions.badmodel system/fvOptions
        shift
        ;;
    -axisdown)
        cp system/fvOptions.axisdown system/fvOptions
        shift
        ;;
    -axisdown-on)
        cp system/fvOptions.axisdown.on system/fvOptions
        shift
        ;;
esac

# Copy initial conditions
cp -rf 0.org 0

runApplication blockMesh
runApplication topoSet

if [ "$1" = "-parallel" ]
then
    runApplication decomposePar
    runParallel pimpleFoam
else
    runApplication pimpleFoam
fi

# ----------------------------------------------------------------- end-of-file
