/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright held by original author(s)
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of turbinesFoam, which is based on OpenFOAM.

    OpenFOAM is free software: you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM.  If not, see <http://www.gnu.org/licenses/>.

\*---------------------------------------------------------------------------*/

// * * * * * * * * * * * * * * * * Member Functions  * * * * * * * * * * * * //

inline const Foam::fv::bladeSurfaceSampler&
Foam::fv::bladeSurfaceSource::sampler() const
{
    return sampler_;
}


inline bool Foam::fv::bladeSurfaceSource::active() const
{
    return true;
}


inline void Foam::fv::bladeSurfaceSource::rotate
(
    const point& rotationPoint,
    const vector& axis,
    const scalar radians
)
{
    sampler_.rotate(rotationPoint, axis, radians);
}


inline void Foam::fv::bladeSurfaceSource::translate(const vector& translation)
{
    sampler_.translate(translation);
}


inline void Foam::fv::bladeSurfaceSource::pitch(const scalar radians)
{
    sampler_.pitch(radians);
}


inline void Foam::fv::bladeSurfaceSource::initializeFsiGeometry()
{
    sampler_.initializeFsiGeometry();
}


inline void Foam::fv::bladeSurfaceSource::fsiUpdateGeometry()
{
    sampler_.fsiUpdateGeometry();
}


// ************************************************************************* //
